<a href="https://colab.research.google.com/github/divya-dataengineer/data-engineer-playbook/blob/main/day1_dataframe_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pyspark

Requirement already satisfied: pyspark in /usr/local/lib/python3.12/dist-packages (4.0.2)
Requirement already satisfied: py4j<0.10.9.10,>=0.10.9.7 in /usr/local/lib/python3.12/dist-packages (from pyspark) (0.10.9.9)

In [ ]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("Day1").getOrCreate()

In [ ]:
#create sample data

data = [ (1, "Divya", 28, 50000),
         (2, "Keerthi", 27, 40000),
         (3, "Uday", 34, 100000),
         (4, "Kumar", 28, 50000) ]

columns = ["ID", "Name", "Age", "Salary"]

df = spark.createDataFrame(data, columns)

df.show()

+---+-------+---+------+
| ID|   Name|Age|Salary|
+---+-------+---+------+
|  1|  Divya| 28| 50000|
|  2|Keerthi| 27| 40000|
|  3|   Uday| 34|100000|
|  4|  Kumar| 28| 50000|
+---+-------+---+------+

In [ ]:
#basic operations
#1. select columns

df.select("ID", "Name").show()

+---+-------+
| ID|   Name|
+---+-------+
|  1|  Divya|
|  2|Keerthi|
|  3|   Uday|
|  4|  Kumar|
+---+-------+

In [ ]:
#2. filter Data

df.filter(df.Salary > 50000).show()

+---+----+---+------+
| ID|Name|Age|Salary|
+---+----+---+------+
|  3|Uday| 34|100000|
+---+----+---+------+

In [ ]:
#3. Add new column

from pyspark.sql.functions import col

df = df.withColumn("Salary_in_n", col("Salary")/1000)
df.show()

+---+-------+---+------+-----------+
| ID|   Name|Age|Salary|Salary_in_n|
+---+-------+---+------+-----------+
|  1|  Divya| 28| 50000|       50.0|
|  2|Keerthi| 27| 40000|       40.0|
|  3|   Uday| 34|100000|      100.0|
|  4|  Kumar| 28| 50000|       50.0|
+---+-------+---+------+-----------+

In [ ]:
df.show()

+---+-------+---+------+-----------+
| ID|   Name|Age|Salary|Salary_in_n|
+---+-------+---+------+-----------+
|  1|  Divya| 28| 50000|       50.0|
|  2|Keerthi| 27| 40000|       40.0|
|  3|   Uday| 34|100000|      100.0|
|  4|  Kumar| 28| 50000|       50.0|
+---+-------+---+------+-----------+

In [ ]:
#4. Rename Column

df = df.withColumnRenamed("Name", "Employee_name")
df.show()

+---+-------------+---+------+-----------+
| ID|Employee_name|Age|Salary|Salary_in_n|
+---+-------------+---+------+-----------+
|  1|        Divya| 28| 50000|       50.0|
|  2|      Keerthi| 27| 40000|       40.0|
|  3|         Uday| 34|100000|      100.0|
|  4|        Kumar| 28| 50000|       50.0|
+---+-------------+---+------+-----------+

In [38]:
#5 drop column

df = df.drop("Salary_in_n")
df.show()

+---+-------------+---+------+
| ID|Employee_name|Age|Salary|
+---+-------------+---+------+
|  1|        Divya| 28| 50000|
|  2|      Keerthi| 27| 40000|
|  3|         Uday| 34|100000|
|  4|        Kumar| 28| 50000|
+---+-------------+---+------+

In [34]:
#6 pandas for better dispaly

df.toPandas()

   ID Employee_name  Age  Salary
0   1         Divya   28   50000
1   2       Keerthi   27   40000
2   3          Uday   34  100000
3   4         Kumar   28   50000

In [42]:
#7 left alligned result (cutting off the spaces)

df.show(truncate=False)

+---+-------------+---+------+
|ID |Employee_name|Age|Salary|
+---+-------------+---+------+
|1  |Divya        |28 |50000 |
|2  |Keerthi      |27 |40000 |
|3  |Uday         |34 |100000|
|4  |Kumar        |28 |50000 |
+---+-------------+---+------+

In [44]:
#8 pandas conversion (every col converts into str)

pdf = df.toPandas().astype(str)
pdf

  ID Employee_name Age  Salary
0  1         Divya  28   50000
1  2       Keerthi  27   40000
2  3          Uday  34  100000
3  4         Kumar  28   50000

In [45]:
#9  left indent using pandas

df.toPandas().style.set_properties(**{'text-align' : 'left'})

In [52]:
#minitasks
#1. Filter employees with salary > 55000
#2. Add bonus column = salary * 0.1
#3. Show only name + bonus

from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("minitasks_of_day1").getOrCreate()

data = [(1, "Divya", 23, 60000), (2, "Keerthi", 25, 50000), (3, "Uday", 28, 100000), (4, "Kumar", 30, 55000) ]
columns = ["ID", "Name", "Age", "Salary"]

df = spark.createDataFrame(data, columns)

df = df.filter(df.Salary >55000)
df.show(truncate=False)

df = df.withColumn("Bonus", col("Salary") * 0.1)
df.show(truncate=False)

df = df.select("Name", "Bonus")
df.show(truncate=False)

+---+-----+---+------+
|ID |Name |Age|Salary|
+---+-----+---+------+
|1  |Divya|23 |60000 |
|3  |Uday |28 |100000|
+---+-----+---+------+

+---+-----+---+------+-------+
|ID |Name |Age|Salary|Bonus  |
+---+-----+---+------+-------+
|1  |Divya|23 |60000 |6000.0 |
|3  |Uday |28 |100000|10000.0|
+---+-----+---+------+-------+

+-----+-------+
|Name |Bonus  |
+-----+-------+
|Divya|6000.0 |
|Uday |10000.0|
+-----+-------+

In [63]:
#10 adding new column

from pyspark.sql import SparkSession
from pyspark.sql.functions import lit

spark = SparkSession.builder.appName("minitasks_of_day1").getOrCreate()

data = [(1, "Divya", 23, 60000), (2, "Keerthi", 25, 50000), (3, "Uday", 28, 100000), (4, "Kumar", 30, 55000) ]
columns = ["ID", "Name", "Age", "Salary"]

df = spark.createDataFrame(data, columns)

df = df.withColumn("Result", lit("Pass"))

df.show(truncate=False)

+---+-------+---+------+------+
|ID |Name   |Age|Salary|Result|
+---+-------+---+------+------+
|1  |Divya  |23 |60000 |Pass  |
|2  |Keerthi|25 |50000 |Pass  |
|3  |Uday   |28 |100000|Pass  |
|4  |Kumar  |30 |55000 |Pass  |
+---+-------+---+------+------+

In [66]:
#11 based on condition

from pyspark.sql.functions import when, col

df = df.withColumn("Result", when(col("Salary") > 50000, "High").otherwise("Low"))

df.show(truncate=False)

+---+-------+---+------+------+
|ID |Name   |Age|Salary|Result|
+---+-------+---+------+------+
|1  |Divya  |23 |60000 |High  |
|2  |Keerthi|25 |50000 |Low   |
|3  |Uday   |28 |100000|High  |
|4  |Kumar  |30 |55000 |High  |
+---+-------+---+------+------+